Lasmart/Models/Entities/Comment.cs
using System.ComponentModel.DataAnnotations;

namespace Lasmart.Models
{
    public class Comment
    {
        [Key]
        [Required]
        public Guid Id { get; set; }

        [Required]
        public string Text { get; set; }

        [Required]
        public string BackgroundColor { get; set; }
        public Point Point { get; set; }
        public Guid PointId { get; set; }
    }
}

Lasmart/Models/Entities/FigureBase.cs
using System.ComponentModel.DataAnnotations;

namespace Lasmart.Models.Entities
{
    public class FigureBase
    {
        [Key]
        [Required]
        public Guid Id { get; set; }

        [Required]
        public float CoordinateX { get; set; }

        [Required]
        public float CoordinateY { get; set; }

        [Required]
        public string Color { get; set; }

        public List<Comment> Comments { get; set; }
    }
}

Lasmart/Models/Entities/Point.cs
using Lasmart.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace Lasmart.Models
{
    public class Point : FigureBase
    {
        [Required]
        public float Radius { get; set; }
    }
}

Lasmart/Models/ErrorViewModel.cs
namespace Lasmart.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lasmart/Controllers/HomeController.cs
using Lasmart.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lasmart.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lasmart/Controllers/PointController.cs
using Lasmart.DataService;
using Microsoft.AspNetCore.Mvc;

namespace Lasmart.Controllers
{
    public class PointController : Controller
    {
        public DataManager _dataManager;

        public PointController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }
        public IActionResult Index()
        {
            var points = _dataManager.PointService.GetPoints();
            return View(points);
        }

        [HttpPost]
        public async Task<IActionResult> Index(Guid id) 
        {
            await _dataManager.PointService.RemovePointAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Lasmart/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lasmart/Views/Point/Index.cshtml
@using System.Web.Helpers;
@model IQueryable<Point>

<h1>Points:</h1>

<script src="https://unpkg.com/konva@8/konva.min.js">

</script>
    
    <div id="container"></div>

    <script>
        var width = window.innerWidth;
        var height = window.innerHeight;
        var stage = new Konva.Stage({
        container: 'container',
        width: width,
        height: height,
        });

        var layer = new Konva.Layer();

    </script>

    @foreach (var item in Model)
    {
        <script>

        var circle = new Konva.Circle({
        x: @item.CoordinateX,
        y: @item.CoordinateY,
        radius: @item.Radius,
        fill: '@item.Color',
        id: '@item.Id',
        });
      
        circle.on('dblclick', function () {
        this.destroy();
        });

        layer.add(circle);
        stage.add(layer);
        </script> 

   @foreach (var onePoint in Model)
   {
       if (onePoint != null)
       {
           <script>
           var offset = @onePoint.Radius *2 ;
           </script>

          @foreach (var comment in onePoint.Comments)
            {
            <script>
            var text = new Konva.Text({
            x: @onePoint.CoordinateX / 2,
            y: @onePoint.CoordinateY + offset,
            text: '@comment.Text',
            fontSize: 20,
            fontFamily: 'Calibri',
            fill: 'green',
            align: 'center',
            });
          
            var rect = new Konva.Rect({
            x: @onePoint.CoordinateX / 2,
            y: @onePoint.CoordinateY + offset,
            fill: '@comment.BackgroundColor',
            width: text.width() + 3,
            height: text.height() + 3,
            opacity: 0.2,
            stroke: '#555',
            strokeWidth: 2,
            });

            offset = offset + 35;

            layer.add(rect);
            layer.add(text);
      
            stage.add(layer);
            </script>
            }
       }
   }
}

Lasmart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lasmart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lasmart.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lasmart</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Point" asp-action="Index">Point</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Lasmart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>